version: '3.9'

services:

  ytc-backend-prod:
    # YTC Backend service: Django ORM
    container_name: ytc-backend-prod
    image: cashmyers/ytc-backend-prod
    build:
      context: .
      dockerfile: ./Dockerfile
    command:
      [
        sh,
        -cx,
        'python ./drf_jwt_backend/manage.py runserver 0.0.0.0:8000'
      ]
    ports:
      - 80:8000
