version: '3.9'

services:
  ytc-backend-prod:
    # YTC Backend service: Django ORM
    container_name: ytc-backend-prod
    image: ytcbackend
    command: 
      [
        sh,
        -cx,
        'python ./drf_jwt_backend/manage.py runserver localhost:8000'
      ]
    ports:
      - 8000:8000