version: '3.9'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - production_db_volume:/var/lib/mysql
    env_file:
      - .live.env

  adminer:
    image: adminer
    restart: always
    volumes:
      - production_db_volume:/var/lib/mysql
    ports:
      - 8085:8080

  ytc-backend-prod:
    container_name: ytc-backend-prod
    image: ytc-backend-prod
    build:
      context: .
      dockerfile: ./Dockerfile
    # command: python ./drf_jwt_backend/manage.py runserver 0.0.0.0:8000
    command: sh ./entrypoint.sh
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  production_db_volume:
